name: Release on main push

## This workflow is triggered on pushes to the main branch.
## It creates a new release with an incremented minor version number
## based on the latest tag found in the repository.
## The release is created using the softprops/action-gh-release action.
# The workflow uses the GITHUB_TOKEN secret to authenticate with the GitHub API.
# The workflow checks out the code, sets up Git user information,
# fetches the latest tag, calculates the next minor version,
# and creates a new release with the specified tag name and release notes.
permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Calculate next minor version
        id: next_version
        run: |
          latest_tag=${{ steps.get_tag.outputs.latest_tag }}
          version=${latest_tag#v}
          IFS='.' read -r major minor patch <<< "$version"
          minor=$((minor+1))
          next_version="v$major.$minor.0"
          echo "next_version=$next_version" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.next_version.outputs.next_version }}
          name: Release ${{ steps.next_version.outputs.next_version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
